---
og:description: Describes how to handle errors and troubleshoot when using your database
  as an identity provider.
og:image: https://cdn2.auth0.com/docs/1.14553.0/img/share-image.png
og:title: Dépanner les bases de données sur mesure
og:url: https://auth0.com/docs/
permalink: error-handling
title: Dépanner les bases de données sur mesure
twitter:description: Describes how to handle errors and troubleshoot when using your
  database as an identity provider.
twitter:title: Dépanner les bases de données sur mesure
---

Vous pouvez retourner les erreurs résultant de votre connexion à la base de données personnalisée à des fins de dépannage. Nous aborderons également quelques étapes de dépannage de base pour vos scripts.

## Types of errors (Types d’erreurs)

Vous pouvez recevoir différents types d’erreurs lors d’une connexion à une base de données :

<table class="table"><thead>
<tr>
<th>Error</th>
<th>Login Script</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>new WrongUsernameOrPasswordError(&lt;email or user_id&gt;, &lt;message&gt;)</code></td>
<td>Login</td>
<td>Occurs when the user's credentials are invalid. Passing no arguments or a falsey first argument will result in the error being logged as an <code>fu</code> event (invalid username/email) with an empty string for a <code>user_id</code>. Providing a truthy first argument will result in the error being logged as an <code>fp</code> event (the user exists, but the password is invalid) with a <code>user_id</code> value of <code>auth0|&lt;first argument&gt;</code>. To learn more, read <a href="/docs/deploy-monitor/logs/log-event-type-codes">Log Event Type Codes</a>.</td>
</tr>
<tr>
<td><code>new ValidationError(&lt;user_exists&gt;, &lt;message&gt;)</code></td>
<td>Create</td>
<td>Occurs when a user already exists in your database.</td>
</tr>
<tr>
<td><code>callback(&lt;null&gt;,&lt;false&gt;)</code></td>
<td>Change Password</td>
<td>Occurs when the user's password was not updated.</td>
</tr>
<tr>
<td><code>callback(&lt;null&gt;)</code></td>
<td>Get User</td>
<td>Occurs when the user is not found.</td>
</tr>
<tr>
<td><code>new UnauthorizedError(&lt;message&gt;)</code></td>
<td>All Login Scripts</td>
<td>Occurs when something went wrong while trying to reach the database. Preferred way of communicating errors back from custom databases to front-end.</td>
</tr>
<tr>
<td><code>new Error(&lt;message&gt;)</code></td>
<td>All Login Scripts</td>
<td>Occurs when something went wrong while trying to reach the database.</td>
</tr>
<tr>
<td><code>error code: auth0_idp_error; user already exists</code></td>
<td>Create</td>
<td>Occurs in legacy identity store when you attempt to create a user that already exists in your legacy identity store or in Auth0.</td>
</tr>
<tr>
<td><code>error code: auth0_idp_error; user already exists</code></td>
<td>Delete</td>
<td>Occurs in legacy identity store when you attempt to delete a user with custom database scripts. Error could also manifest as <code>Error! There was a problem deleting user@example.com</code> or <code>Sandbox Error: Please implement the Delete script for this database connection at https://manage.auth0.com/#/connections/database</code>.</td>
</tr>
</tbody>
</table>

## Renvoyer une erreur

Pour retourner une erreur, faites une requête à la fonction **callback** en y passant **error** comme premier paramètre :

```js lines
callback(error);
```






Example:

```js wrap lines
callback(new ValidationError('email-too-long', 'Email is too long.'));
```






### Retourner des erreurs lors de l’utilisation de Lock

If you use Lock, you can [customize the error messages](/docs/customize/login-pages/classic-login/customize-lock-error-messages) that will be displayed by adding them to the dictionary.

## Dépannage des erreurs

Testez le script à l’aide du bouton **Try** (Essayer).

If you do not get the expected result or you receive an error, install the [Real-time Webtask Logs extension](/docs/customize/extensions/real-time-webtask-logs), use `console.log()` statements in your script, and try the connection again. The output of `console.log()` will print to the Real-time Webtask Logs window.

You may experience errors using action scripts to import, create, or delete users. Use `console.logs` to verify the error is a result of using action scripts. To learn more, read [Custom Database Action Script Templates](/docs/authenticate/database-connections/custom-db/templates).